name: lildazzle
favicon: null
layout_spectrum: 0.93322
typography_spectrum: 0.16395
title: "L'il Dazzle Online Store"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dacbb9'
    - '#ab8b75'
    - '#e30040'
    - '#00afc2'
    - '#ff5a71'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
