name: lildazzle
favicon: null
layout_spectrum: 0.8031280608847737
typography_spectrum: 0.4110201362054795
title: "L'il Dazzle Online Store"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6232190243899822
  lightness: 0.11721733771264553
  saturation: 0.8197934068739414
  rhythmicContrast: 0.8441545686218888
purpose: []
