name: lildazzle
favicon: null
layout_spectrum: 0.93322
typography_spectrum: 0.16395
title: "L'il Dazzle Online Store"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6bea9'
    - '#a99a88'
    - '#0f0a1d'
    - '#efe7dc'
    - '#4c4643'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
